spring:
  datasource:
    url: jdbc:mysql://47.95.10.169:3306/pp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Zhzr66@$
    driver-class-name: com.mysql.jdbc.Driver

file.uplode.type: offline

